/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmln_PID */

#ifndef _Included_jmln_PID
#define _Included_jmln_PID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmln_PID
 * Method:    l
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jmln_PID_l
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
